package io.github.bernardusz.booking_ticketing.showings.dto

import io.github.bernardusz.booking_ticketing.auditoriums.Auditorium
import io.github.bernardusz.booking_ticketing.languages.Language
import io.github.bernardusz.booking_ticketing.movies.Movie
import io.github.bernardusz.booking_ticketing.showings.Showing
import io.github.bernardusz.booking_ticketing.showings.ShowingSpecification
import jakarta.persistence.criteria.JoinType
import org.springframework.data.jpa.domain.Specification
import java.math.BigDecimal
import java.time.OffsetDateTime

data class ShowingSummaryResponse(
    val id: Long,
    val startTime: OffsetDateTime,
    val price: BigDecimal,
    val movieId: Long,
    val movieTitle: String,
    val durationMinutes: Int,
    val posterUrl: String?,
    val auditoriumCode: String,
    val auditoriumName: String,
    val languageCode: String,
    val languageTitle: String,
    val availableSeatsCount: Int? = null
)

fun ShowingSpecification.fetchRelations(): Specification<Showing> {
    return Specification { root, query, cb ->
        // Avoid duplicate rows in count queries generated by pagination
        if (query?.resultType != Long::class.java) {
            root.fetch<Showing, Movie>("movie", JoinType.LEFT)
            root.fetch<Showing, Auditorium>("auditorium", JoinType.LEFT)
            root.fetch<Showing, Language>("language", JoinType.LEFT)
        }
        cb.conjunction()
    }
}

fun Showing.toSummary(): ShowingSummaryResponse = ShowingSummaryResponse(
    id = this.id,
    startTime = this.startTime,
    price = this.price,
    movieId = this.movie.id,
    movieTitle = this.movie.title,
    durationMinutes = this.movie.durationMinutes,
    posterUrl = this.movie.posterUrl,
    auditoriumCode = this.auditorium.code,
    auditoriumName = this.auditorium.name,
    languageCode = this.language.code,
    languageTitle = this.language.title,
    availableSeatsCount = this.auditorium.totalSeats
)